# use container-based infrastructure
sudo: false

language: c

# treat all warnings as errors
env: CFLAGS=-Werror

os:
  - linux
  - osx
compiler:
  - gcc
  - clang

# OSX uses Apple's flavor of clang anyway, so there's no point in trying "gcc".
# This excludes the "gcc" compiler from the build matrix for OSX:
matrix:
  exclude:
    - os: osx
      compiler: gcc

# take care of the libusb dependency for Linux
addons:
  apt:
    packages:
    - libusb-1.0-0-dev

# take care of the libusb dependency for Mac OS X; on Linux use "make all" later
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install libusb;
    else
      export TARGET="all CROSS_COMPILE=";
    fi

# build using the Makefile
script:
  - make ${TARGET} && make misc

# when on Linux: run/simulate a test install
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make install-all install-misc DESTDIR=/tmp PREFIX=/sunxi-tools;
    fi

# turn off email notifications
notifications:
  - email: false
