# use container-based infrastructure
sudo: false

language: c

os:
  - linux
  - osx
compiler:
  - gcc
  - clang

# OSX uses Apple's flavor of clang anyway, so there's no point in using "gcc".
# This excludes the "gcc" compiler from the build matrix for OSX:
matrix:
  exclude:
    - os: osx
      compiler: gcc

# take care of the libusb dependency for Linux
addons:
  apt:
    packages:
    - libusb-1.0-0-dev

# take care of the libusb dependency for Mac OS X
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install libusb;
    fi

# build by simply using the Makefile
script:
  - make
  - make misc

# turn off email notifications
notifications:
  - email: false
